version: '3.8'

services:
  jit-bot:
    build: .
    container_name: jit-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - '3000:3000'
    depends_on:
      - redis
    networks:
      - jit-network

  redis:
    image: redis:7-alpine
    container_name: jit-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - jit-network

  # Optional: Erigon node (commented out by default)
  # erigon:
  #   image: thorax/erigon:latest
  #   container_name: jit-erigon
  #   restart: unless-stopped
  #   command: erigon --chain=mainnet --datadir=/data --http --http.api=eth,debug,net,trace,web3 --http.addr=0.0.0.0 --http.port=8545 --ws --ws.addr=0.0.0.0 --ws.port=8546
  #   ports:
  #     - "8545:8545"
  #     - "8546:8546"
  #   volumes:
  #     - erigon_data:/data
  #   networks:
  #     - jit-network

  # Optional: Geth node (commented out by default)
  # geth:
  #   image: ethereum/client-go:latest
  #   container_name: jit-geth
  #   restart: unless-stopped
  #   command: --http --http.api=eth,net,web3 --http.addr=0.0.0.0 --http.port=8545 --ws --ws.api=eth,net,web3 --ws.addr=0.0.0.0 --ws.port=8546
  #   ports:
  #     - "8545:8545"
  #     - "8546:8546"
  #   volumes:
  #     - geth_data:/root/.ethereum
  #   networks:
  #     - jit-network

volumes:
  redis_data:
  # erigon_data:
  # geth_data:

networks:
  jit-network:
    driver: bridge
